local:
  hosts:
    localhost:
      ansible_connection: local
vm01:
  vars:
    vms_path: "HOME/other"
  hosts:
    192.168.33.10:
      ansible_connection: ssh
      ansible_user: vagrant
      ansible_ssh_private_key_file: "{{vms_path}}/vm01/.vagrant/machines/default/virtualbox/private_key"
vm02:
  vars:
    vms_path: "HOME/other"
  hosts:
    192.168.33.11:
      ansible_connection: ssh
      ansible_user: vagrant
      ansible_ssh_private_key_file: "{{vms_path}}/vm02/.vagrant/machines/default/virtualbox/private_key"
vm03:
  vars:
    vms_path: "HOME/other"
  hosts:
    192.168.33.12:
      ansible_connection: ssh
      ansible_user: vagrant
      ansible_ssh_private_key_file: "{{vms_path}}/vm03/.vagrant/machines/default/virtualbox/private_key"
vagrant:
  children:
    vm01:
    vm02:
    vm03:
all:
  children:
    local:
    vm01:
    vm02:
    vm03:
